### ISSUE TITLE
taal app

### ISSUE THREAD

**Issue by Rellor** [Tomvandenberg11/PTTeam#16]
We hebben in onze app bepaalde woorden engels en bepaalde woorden nederlands staan. We moeten ons houden aan een taal

**Comment by wongsrila** [comment]
Gaan we Engels aanhouden?

**Comment by Tomvandenberg11** [comment]
Ik denk dat het meeste Nederlands is dus misschien moeten we Nederlands aanhouden

**Comment by Rellor** [comment]
Alles staat (zo ver ik weet) nu in het nederlands
