### ISSUE TITLE
Chat scrolled niet mee

### ISSUE THREAD

**Issue by Rellor** [Tomvandenberg11/PTTeam#22]
Als je praat in de chat gaat de chat niet mee met jou als gebruiker

**Comment by Tomvandenberg11** [comment]
Je kan proberen om een div om de chat te doen en dan op die div 
```
overflow: scroll;
height: 600px;
```
te zetten. Ik hoop dat het zo kan werken

**Comment by Tomvandenberg11** [comment]
Issue is gefixt!
